### ISSUE TITLE
Chat error

### ISSUE THREAD

**Issue by oddbaijanian** [happyredstone/sodiumplus#19]
"Recieved a chat packet with missing or invalid signaturet"

**Comment by NoSadBeHappy** [comment]
A temporary solution is to remove the mod "no chat reports" I am trying to find a full solution.

**Comment by RedstoneWizard08** [comment]
Yeah me too. I was testing plugin dev and I couldn't send chat messages.

**Comment by NoSadBeHappy** [comment]
I have submitted an issue on the no-chat-reports github: https://github.com/Aizistral-Studios/No-Chat-Reports/issues/423

**Comment by RedstoneWizard08** [comment]
This should hopefully be fixed, I haven't tested it but everything was updated in v2.2.10.

**Comment by RedstoneWizard08** [comment]
This should be fixed in v3, we are moving back to Fabric and not Quilt

**Comment by NoSadBeHappy** [comment]
Although it is not v3 yet, we have moved back to fabric, so this should no longer be an issue. Feel free to reopen if you still have this issue in the new versions of the pack.
