### ISSUE TITLE
Plug / Disconnect Icon in bottom left corner

### ISSUE THREAD

**Issue by GhostJumper** [happyredstone/sodiumplus#24]
Hey,
I was wondering what this Icon in the bottom left of my screen means exactly.
What mod does it belong to & do I need to add that mod to my fabric server?

![image](https://github.com/happyredstone/sodiumplus/assets/34964243/a2c0bdf7-b794-4a48-8e74-eb79e9898ee3)

**Comment by NoSadBeHappy** [comment]
This icon is from Simple Voice Chat (https://modrinth.com/plugin/simple-voice-chat) It just means that the server you are connected to doesen't have the plugin needed to use the mod. If you want to remove it, im 90% sure you can change the setting in the mods menu to not show the symbol.

**Comment by RedstoneWizard08** [comment]
Press [V] (by default) to open Simple Voice Chat settings. You can hide icons from there.
