### ISSUE TITLE
crashing on start

### ISSUE THREAD

**Issue by 41chemist** [happyredstone/sodiumplus#26]
haven't been able to start Minecraft when launching with this modpack. here's the crash report. 

---- Minecraft Crash Report ----
// You're mean.

Time: 2024-04-01 04:40:49
Description: Initializing game

java.lang.UnsupportedOperationException: ERROR: Unable to create a GL Context using any of the supported GL versions: [(4, 6),(4, 5),(4, 4),(4, 3),(4, 2),(4, 1),(4, 0),(3, 3),(3, 2)]
	at com.seibel.distanthorizons.core.render.glObject.GLProxy.<init>(GLProxy.java:263)
	at com.seibel.distanthorizons.core.render.glObject.GLProxy.getInstance(GLProxy.java:442)
	at com.seibel.distanthorizons.core.api.internal.ClientApi.rendererStartupEvent(ClientApi.java:279)
	at net.minecraft.class_757.handler$zgo000$distanthorizons$onStartupShaders(class_757.java:2118)
	at net.minecraft.class_757.method_34521(class_757.java:480)
	at net.minecraft.class_310.<init>(class_310.java:633)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.seibel.distanthorizons.core.render.glObject.GLProxy.<init>(GLProxy.java:263)
	at com.seibel.distanthorizons.core.render.glObject.GLProxy.getInstance(GLProxy.java:442)
	at com.seibel.distanthorizons.core.api.internal.ClientApi.rendererStartupEvent(ClientApi.java:279)
	at net.minecraft.class_757.handler$zgo000$distanthorizons$onStartupShaders(class_757.java:2118)
	at net.minecraft.class_757.method_34521(class_757.java:480)
	at net.minecraft.class_310.<init>(class_310.java:633)
Mixins in Stacktrace:
	net.minecraft.class_757:
		net.raphimc.immediatelyfast.injection.mixins.core.compat.MixinGameRenderer (#immediatelyfast:immediatelyfast-common.mixins.json)
		dev.notalpha.dashloader.mixin.option.cache.shader.GameRendererMixin (#dashloader:dashloader.mixins.json)
		org.quiltmc.qsl.resource.loader.mixin.client.KeyedClientResourceReloaderMixin (#quilt_resource_loader:quilt_resource_loader.mixins.json)
		net.fabricmc.fabric.mixin.client.rendering.shader.GameRendererMixin (#quilted_fabric_rendering_v1:quilted_fabric_rendering_v1.mixins.json)
		net.coderbot.iris.mixin.MixinGameRenderer_NightVisionCompat (#iris:mixins.iris.json)
		ladysnake.satin.mixin.client.event.GameRendererMixin (#satin:mixins.satin.client.json)
		me.jellysquid.mods.sodium.mixin.features.gui.hooks.console.GameRendererMixin (#sodium:sodium.mixins.json)
		dev.isxander.zoomify.mixins.zoom.GameRendererMixin (#zoomify:zoomify.mixins.json)
		xaero.common.mixin.MixinGameRenderer (#xaerominimap:xaerohud.mixins.json)
		org.quiltmc.qsl.screen.mixin.client.GameRendererMixin (#quilt_screen:quilt_screen.mixins.json)
		dynamic_fps.impl.mixin.GameRendererMixin (#dynamic_fps:dynamic_fps-common.mixins.json)
		dev.isxander.zoomify.mixins.zoom.secondary.GameRendererMixin (#zoomify:zoomify.mixins.json)
		traben.entity_model_features.mixin.MixinGameRenderer (#entity_model_features:entity_model_features-common.mixins.json)
		net.coderbot.iris.mixin.MixinGameRenderer (#iris:mixins.iris.json)
		xaero.map.mixin.MixinGameRenderer (#xaeroworldmap:xaeroworldmap.mixins.json)
		dev.architectury.mixin.fabric.client.MixinGameRenderer (#architectury:architectury.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.prevent_shaders.MixinGameRenderer (#sodium-extra:sodium-extra.mixins.json)
		com.seibel.distanthorizons.fabric.mixins.client.MixinGameRenderer (#distanthorizons:fabric-DistantHorizons.fabric.mixins.json)
		team.lodestar.lodestone.mixin.GameRendererMixin (#lodestone:lodestone.mixins.json)
		net.coderbot.iris.mixin.MixinModelViewBobbing (#iris:mixins.iris.json)
		net.coderbot.iris.mixin.GameRendererAccessor (#iris:mixins.iris.json)
	net.minecraft.class_310:
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (#quilted_fabric_data_generation_api_v1:quilted_fabric_data_generation_api_v1.client.mixins.json)
		opekope2.optigui.mixin.MinecraftClientMixin2 (#optigui:optigui.mixins.json)
		io.grayray75.mods.fpsdisplay.mixin.MinecraftClientAccessor (#fpsdisplay:fpsdisplay.mixins.json)
		me.ramidzkh.fabrishot.mixins.MinecraftClientMixin (#fabrishot:mixins.fabrishot.json)
		traben.entity_model_features.mixin.MixinResourceReload (#entity_model_features:entity_model_features-common.mixins.json)
		io.github.xiaocihua.stacktonearbychests.mixin.MinecraftClientMixin (#stack-to-nearby-chests:stacktonearbychests.mixins.json)
		net.raphimc.immediatelyfast.injection.mixins.core.MixinMinecraftClient (#immediatelyfast:immediatelyfast-common.mixins.json)
		io.github.cottonmc.cotton.gui.impl.mixin.client.MinecraftClientMixin (#libgui:mixins.libgui.json)
		fi.dy.masa.litematica.mixin.MixinMinecraftClient (#litematica:mixins.litematica.json)
		ca.fxco.moreculling.mixin.MinecraftClient_managersMixin (#moreculling:moreculling.mixins.json)
		de.florianmichael.viafabricplus.injection.mixin.base.MixinMinecraftClient (#viafabricplus:viafabricplus.mixins.json)
		ladysnake.satin.mixin.client.event.MinecraftClientMixin (#satin:mixins.satin.client.json)
		org.quiltmc.qsl.lifecycle.mixin.client.MinecraftClientMixin (#quilt_lifecycle_events:quilt_lifecycle_events.mixins.json)
		dev.isxander.zoomify.mixins.hooks.MinecraftClientMixin (#zoomify:zoomify.mixins.json)
		traben.entity_model_features.mixin.accessor.MinecraftClientAccessor (#entity_model_features:entity_model_features-common.mixins.json)
		org.quiltmc.qsl.resource.loader.mixin.client.MinecraftClientMixin (#quilt_resource_loader:quilt_resource_loader.mixins.json)
		com.minelittlepony.common.mixin.MixinMinecraftClient (#kirin:kirin.mixin.json)
		dev.chachy.lazylanguageloader.client.mixin.optimizations.splash.MixinMinecraftClient (#lazy-language-loader:lazy-language-loader.mixin.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (#ferritecore:ferritecore.fabric.mixin.json)
		com.aizistral.nochatreports.common.mixins.client.MixinMinecraft (#nochatreports:mixins/common/nochatreports.mixins.json)
		dev.lambdaurora.lambdynlights.mixin.MinecraftClientMixin (#lambdynlights:lambdynlights.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Keybinds (#iris:mixins.iris.json)
		org.quiltmc.qsl.networking.mixin.accessor.MinecraftClientAccessor (#quilt_networking:quilt_networking.mixins.json)
		ca.fxco.memoryleakfix.mixin.targetEntityLeak.Minecraft_targetClearMixin (#memoryleakfix:memoryleakfix.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Images (#iris:mixins.iris.json)
		de.florianmichael.viafabricplus.injection.mixin.fixes.minecraft.MixinMinecraftClient (#viafabricplus:viafabricplus.mixins.json)
		dev.isxander.yacl3.mixin.MinecraftMixin (#yet_another_config_lib_v3:yacl.mixins.json)
		org.quiltmc.qsl.command.mixin.client.MinecraftClientMixin (#quilt_client_command:quilt_client_command.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (#quilted_fabric_registry_sync_v0:quilted_fabric_registry_sync_v0.client.mixins.json)
		com.kingcontaria.fastquit.mixin.MinecraftClientAccessor (#fastquit:fastquit.mixins.json)
		opekope2.optigui.mixin.MinecraftClientMixin (#optigui:optigui.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.MinecraftClientMixin (#sodium:sodium.mixins.json)
		org.quiltmc.qsl.base.mixin.client.MinecraftClientMixin (#quilt_base:quilt_base.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (#iris:mixins.iris.json)
		traben.entity_texture_features.mixin.reloading.MixinMinecraftClient (#entity_texture_features:entity_texture_features-common.mixins.json)
		com.natamus.collective.fabric.mixin.MinecraftMixin (#collective:collective_fabric.mixins.json)
		jerozgen.languagereload.mixin.MinecraftClientAccessor (#languagereload:languagereload.mixins.json)
		ca.fxco.moreculling.mixin.blockstates.MinecraftClient_loadBlocksMixin (#moreculling:moreculling.mixins.json)
		org.quiltmc.qsl.screen.mixin.client.MinecraftClientMixin (#quilt_screen:quilt_screen.mixins.json)
		de.siphalor.amecs.impl.mixin.MixinMinecraftClient (#amecsapi:amecsapi.mixins.json)
		xaero.map.mixin.MixinMinecraftClient (#xaeroworldmap:xaeroworldmap.mixins.json)
		org.quiltmc.qsl.registry.mixin.client.MinecraftClientMixin (#quilt_registry:quilt_registry.mixins.json)
		com.seibel.distanthorizons.fabric.mixins.client.MixinMinecraft (#distanthorizons:fabric-DistantHorizons.fabric.mixins.json)
		com.kingcontaria.fastquit.mixin.MinecraftClientMixin (#fastquit:fastquit.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (#quilted_fabric_events_interaction_v0:quilted_fabric_events_interaction_v0.client.mixins.json)
		ca.fxco.memoryleakfix.mixin.hugeScreenshotLeak.Minecraft_screenshotMixin (#memoryleakfix:memoryleakfix.mixins.json)
		de.maxhenkel.voicechat.mixin.MinecraftMixin (#voicechat:voicechat.mixins.json)
		dynamic_fps.impl.mixin.MinecraftMixin (#dynamic_fps:dynamic_fps-common.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (#sodium-extra:sodium-extra.mixins.json)
		fi.dy.masa.malilib.mixin.MixinMinecraftClient (#malilib:mixins.malilib.json)
		dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (#spruceui:spruceui.mixins.json)
		de.siphalor.mousewheelie.client.mixin.MixinMinecraftClient (#mousewheelie:mousewheelie.mixins.json)
		jerozgen.languagereload.mixin.MinecraftClientMixin (#languagereload:languagereload.mixins.json)
		com.tterrag.blur.mixin.MixinMinecraftClient (#blur:mixins.blur.json)
		shcm.shsupercm.fabric.citresewn.defaults.mixin.types.enchantment.MinecraftClientMixin (#citresewn-defaults:citresewn-defaults.mixins.json)
		xaero.common.mixin.MixinMinecraftClient (#xaerominimap:xaerohud.mixins.json)
		dev.notalpha.dashloader.mixin.main.MinecraftClientMixin (#dashloader:dashloader.mixins.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (#architectury:architectury.mixins.json)
		fuzs.forgeconfigapiport.mixin.client.MinecraftMixin (#forgeconfigapiport:forgeconfigapiport.common.mixins.json)
		com.aizistral.nochatreports.fabric.mixins.client.MixinMinecraft (#nochatreports:mixins/fabric/nochatreports-fabric.mixins.json)
		team.lodestar.lodestone.mixin.MinecraftClientMixin (#lodestone:lodestone.mixins.json)
		squeek.appleskin.mixin.MinecraftClientMixin (#appleskin:appleskin.mixins.json)
		randommcsomethin.fallingleaves.mixin.MinecraftClientMixin (#fallingleaves:fallingleaves.mixins.json)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Mixins in Stacktrace:
	net.minecraft.client.main.Main:
		de.florianmichael.viafabricplus.injection.mixin.base.MixinMain (#viafabricplus:viafabricplus.mixins.json)
		dev.notalpha.dashloader.mixin.main.MainMixin (#dashloader:dashloader.mixins.json)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.15.0-101-generic
	Java Version: 17.0.10, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 323617408 bytes (308 MiB) / 1317011456 bytes (1256 MiB) up to 10485760000 bytes (10000 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900X 12-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: Device
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x73a5
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 34166.32
	Virtual memory used (MB): 4766.90
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx10000m

**Comment by RedstoneWizard08** [comment]
Your OpenGL version is not supported. What hardware are you using, @41chemist ?

**Comment by RedstoneWizard08** [comment]
Iirc AMD hardware doesn't work well with Distant Horizons. Try removing that mod.

**Comment by 41chemist** [comment]
that fixed it, thank you so much.

is there a way to get it working on AMD cards though?

**Comment by RedstoneWizard08** [comment]
This is a known issue and there seem to be steps to fix it. Look here: https://gitlab.com/jeseibel/distant-horizons/-/issues/581#chcek-off-each-item-in-this-list-before-submitting

**Comment by NoSadBeHappy** [comment]
I have an AMD GPU, I will try this fix later today and get back to you.

**Comment by NoSadBeHappy** [comment]
Sorry for not responding to this, I believe the newest version of the pack fixes this problem. If it is still an issue, feel free to reopen.
