### ISSUE TITLE
When can we expect 1.20.4 update for this modpack?

### ISSUE THREAD

**Issue by asabhi6776** [happyredstone/sodiumplus#27]
Hi Dev, thanks for making this modpack. I love this so much, but now due to some reason i need to switch to 1.20.4 version, but sodiumplus does not have that version. I don't want to move to any other modpack since i am very comfortable with this. 

Can i get some expected time when can we get 1.20.4 release for this,

Thanks

**Comment by NoSadBeHappy** [comment]
Hi! Thanks for your support. I honestly have not worked on the 1.20.4 release at all. I have been busy with school, and with the amount of mods on the pack, it takes a surprisingly long time to update all the mods and get it stable. As I don't have any software to help me I also have to do it manually. 

I hope to update the pack at some point, but for the mean time you should be able to join any 1.20.4 server on the current release.

If you would like to update it yourself it should be possible, just import it, update mc and quilt, and update all mods then try to launch and fix any errors quilt gives you. I just don't have the time to do it right now.

**Comment by asabhi6776** [comment]
I was trying no-trial-chamber datapack but lots of bugs came in like, shulker box was taking too long to break using netherite pickaxe and was not able to break ender_chest at all. 

But no hurry i can wait a little longer.

Thank you so much for making this mod.

**Comment by RedstoneWizard08** [comment]
I'm gonna work on this soon.

**Comment by RedstoneWizard08** [comment]
I'm gonna work on this soon.

**Comment by asabhi6776** [comment]
Thank you soo much

**Comment by NoSadBeHappy** [comment]
Thank you so much @RedstoneWizard08! Sorry for being slow @asabhi6776 and thank you for the support.
