### ISSUE TITLE
update

### ISSUE THREAD

**Issue by GSNinjaMusic** [happyredstone/sodiumplus#29]
update to 1.21

**Comment by NoSadBeHappy** [comment]
Will work on that after I finish going on vacation (a couple weeks) I would have done it sooner but not enough more were supported.

**Comment by GSNinjaMusic** [comment]
> Will work on that after I finish going on vacation (a couple weeks) I would have done it sooner but not enough more were supported.

ok, I hope so, I've always liked this modpack because of the mods it contains (which are many), and I really hope for an update on it

**Comment by NoSadBeHappy** [comment]
There will be, just depends on how long it takes.

**Comment by RedstoneWizard08** [comment]
I'm currently working on a new CLI tool to make it easier to support multiple versions and loaders at the same time, but it's very complex and takes a lot of time to build. We'll try to update it very soon with the existing tools, but I'm also on vacation right now so it won't happen for at least 3 weeks for me. I'll continue working on the tooling though, I can do that from my chromebook. :)

Thanks for your patience.

**Comment by GSNinjaMusic** [comment]
Ok, I hope they update Sodium Plus

**Comment by GSNinjaMusic** [comment]
Ok, I hope they update Sodium Plus

**Comment by RedstoneWizard08** [comment]
Tooling: https://github.com/RedstoneWizard08/Wormhole/tree/main/apps/cli

**Comment by RedstoneWizard08** [comment]
BTW, it's taking so long because I'm migrating from `diesel` to `prisma-client-rust` for the backend database and migrating from `sveltekit` to `nuxt` on the frontend. Sorry it's taking so long, but I'm trying to build good tooling that will last and work really well.

**Comment by RedstoneWizard08** [comment]
@NoSadBeHappy when you get the chance can you make a temporary 1.21 release with prism or something (or the old packwiz system)? Thanks.

**Comment by NoSadBeHappy** [comment]
Yes, of course. I planned on doing it after vacation (ends tomorrow) so I will upload by Monday. I was uld have done it sooner, but there were too many mods without support still.

-------- Original Message --------

**Comment by GSNinjaMusic** [comment]
I found a bug in the newest alpha version, the bug is that the game crashes when the person wants to change the language

**Comment by NoSadBeHappy** [comment]
Thanks for the report, could you do it on a new issue please? Also I am going to close this issue, as it has been resolved.

**Comment by GSNinjaMusic** [comment]
I understand, sorry for talking about the same post, I'll make another post about another bug
