### ISSUE TITLE
Getting in a boat crashes your game

### ISSUE THREAD

**Issue by HuffGLaDTem** [happyredstone/sodiumplus#30]
I just downloaded this pack for the 1.21 update and created a new world, I got in a boat and the game crashed and upon trying to join that world again the program was unresponsive as soon as I loaded in so I had to force quit the game

**Comment by NoSadBeHappy** [comment]
Could you post the relevant logs? I will look into this tomorrow.

**Comment by HuffGLaDTem** [comment]
[crash-2024-07-21_21.50.13-client.txt](https://github.com/user-attachments/files/16326973/crash-2024-07-21_21.50.13-client.txt)
yes sorry here is the crash report I had just remembered that I forgot to post them when you responded. also upon further testing it seems that its when I try and move in the boat, not just when I enter the boat. Thanks!

**Comment by NoSadBeHappy** [comment]
Okay thanks for the information.

**Comment by NoSadBeHappy** [comment]
I was able to replicate this issue, and I figured out it is https://modrinth.com/mod/boat-item-view, most likely because it is not officially supported for 1.21. For now, remove that mod, and the next release will not have it included unless it gets updated.

Thanks for the report!

**Comment by HuffGLaDTem** [comment]
Perfect, thanks!
