### ISSUE TITLE
Game Crashing when starting to ride Boat

### ISSUE THREAD

**Issue by YungZeiro** [happyredstone/sodiumplus#31]
Hello,

me and friend noticed, that when you try to move in a boat, the game crashes. But only when you try to move it, sitting in it works.
Deactivating "Boat Item View Fabric" hotfixes it.

**Comment by NoSadBeHappy** [comment]
Duplicate of https://github.com/happyredstone/sodiumplus/issues/30

**Comment by RedstoneWizard08** [comment]
This seems to have been fixed
